### ISSUE TITLE
Not working with angular 2

### ISSUE THREAD

**Issue by shahkari** [Apercu/adyen-encrypt#4]
After installing using npm i adyen-encrypt.
Trying to use in one of the component but it isnt able to find the module. Is it missing d.ts file ?

**Comment by balthazar** [comment]
There is no typescript definition in this repository

**Comment by shahkari** [comment]
Ok. So when I use it in angular 4 in typescript I import the module and create new object but it throws an error saying AdyenEncrypt is not a constructor.
Code:
const instance = new AdyenEncrypt(key, {
      enableValidations: true,
      numberIgnoreNonNumeric: true,
      cvcIgnoreBins: '101,404'
    });

**Comment by balthazar** [comment]
I'm no Angular expert anymore, but it seems weird that they would force third-party modules to have type definitions. This library is pure Javascript and there might be something else you're doing wrong, and I suspect this is how you are importing the module, if following a require pattern, you need to do the following:

```js
const AdyenEncrypt = require('adyen-encrypt').default
```
